feat(yt-shorts): add youtube shorts downloader service
akali/steplems-bot pull request #4
Opened 2022-01-17 05:48 UTC by arpanetus

2022-01-17 05:53 UTC, arpanetus commented
мында қалай скуош жасаса болад 🤔

2022-01-17 20:23 UTC, akali requested changes

2022-01-17 20:23 UTC, akali commented on app/commands/eval/service.go
> +		text := "free helicopter rides"
please create another PR for this change

2022-01-17 20:23 UTC, akali commented on app/youtube/model.go
> +	ytLinkRegex    = "(((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com))(\\/(shorts\\/))([\\w\\-]+)(\\S+)?)"
What about youtu.be links?

2022-01-17 20:23 UTC, akali commented on app/youtube/model.go
> +	isFailedToFind := true
No need for a separate flag, just set chosenFormat as formats[0] in the beginning

2022-01-17 20:23 UTC, akali commented on app/youtube/model.go
> +	isFailedToFind := true
Or even directly return format if you able to find, otherwise return &formats[0]

2022-01-17 22:53 UTC, arpanetus commented on app/youtube/model.go
> +	ytLinkRegex    = "(((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com))(\\/(shorts\\/))([\\w\\-]+)(\\S+)?)"
why would u need to download another yt videos, it was made for shorts and only

2022-01-17 22:54 UTC, arpanetus commented on app/commands/eval/service.go
> +		text := "free helicopter rides"
this is canon

2022-01-17 22:54 UTC, akali commented
Exactly for shorts sometimes it is been shared with youtu.be link

On Mon, 17 Jan 2022 at 23:53 arpanetus ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/youtube/model.go
> <https://github.com/akali/steplems-bot/pull/4#discussion_r786322239>:
>
> > +
> +const (
> +	HD     QualityType = "hd"
> +	HD720  QualityType = "hd720"
> +	HD1080 QualityType = "hd1080"
> +	MEDIUM QualityType = "medium"
> +)
> +
> +const (
> +	MP4  VideoType = "video/mp4"
> +	MKV  VideoType = "video/mkv"
> +	WEBM VideoType = "video/webm"
> +)
> +
> +var (
> +	ytLinkRegex    = "(((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com))(\\/(shorts\\/))([\\w\\-]+)(\\S+)?)"
>
> why would u need to download another yt videos, it was made for shorts and
> only
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/akali/steplems-bot/pull/4#discussion_r786322239>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABEY3EOZUXPRWNHJATLDSQDUWSMV5ANCNFSM5MDZIUIQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-01-17 22:54 UTC, arpanetus commented on app/youtube/model.go
> +	ytLinkRegex    = "(((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com))(\\/(shorts\\/))([\\w\\-]+)(\\S+)?)"
no one shares yt shorts like youtu.be, lets be honest

2022-01-17 23:14 UTC, akali commented on app/youtube/model.go
> +	ytLinkRegex    = "(((?:https?:)?\\/\\/)?((?:www|m)\\.)?((?:youtube\\.com))(\\/(shorts\\/))([\\w\\-]+)(\\S+)?)"
Whatever

2022-01-18 04:29 UTC, arpanetus commented
@akali қабылдаш енді

2022-01-19 09:52 UTC, merged